version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: maybank-postgres
    environment:
      POSTGRES_DB: maybankdb
      POSTGRES_USER: maybank
      POSTGRES_PASSWORD: maybank123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maybank -d maybankdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: